### ISSUE TITLE
ports are prometheus and grafana not bound to host desktop hence URL open not working

### ISSUE THREAD

**Issue by nagkumar** [resilience4j/resilience4j-spring-boot3-demo#3]
<img width="1278" alt="image" src="https://github.com/resilience4j/resilience4j-spring-boot3-demo/assets/332234/980794bf-7d81-4e15-b64c-5950c445ef6f">

<img width="1059" alt="image" src="https://github.com/resilience4j/resilience4j-spring-boot3-demo/assets/332234/6c5b8ad4-120c-4df7-822a-f0ff51bd549f">

<img width="709" alt="image" src="https://github.com/resilience4j/resilience4j-spring-boot3-demo/assets/332234/c6304363-a1e7-4a12-9e84-e2a8c5805848">

and

<img width="828" alt="image" src="https://github.com/resilience4j/resilience4j-spring-boot3-demo/assets/332234/8e253cdf-ae0a-461a-a6a0-40bb25edb7ee">

**Comment by nagkumar** [comment]
any support as I unable to access graphana and premethos URL

**Comment by RobWin** [comment]
Did you run https://github.com/resilience4j/resilience4j-spring-boot3-demo/blob/master/docker-compose-desktop.yml?

**Comment by nagkumar** [comment]
I have the followed the steps in readme.md

and used command 

`docker-compose -f docker-compose.yml up
`

![image](https://github.com/resilience4j/resilience4j-spring-boot3-demo/assets/332234/3aa90aef-4e45-45a5-adc9-f10f5d9fe873)

**Comment by nagkumar** [comment]
With  _docker-compose-desktop.yml_ instead of `docker-compose.yml`

![image](https://github.com/resilience4j/resilience4j-spring-boot3-demo/assets/332234/1494a4c2-55ff-48d7-b393-0e9c68816a6f)

**Comment by nagkumar** [comment]
> Did you run https://github.com/resilience4j/resilience4j-spring-boot3-demo/blob/master/docker-compose-desktop.yml?

Thank You This works.. only change needed was 

`FROM gradle:latest`

![image](https://github.com/resilience4j/resilience4j-spring-boot3-demo/assets/332234/504ed054-c189-4887-9dd6-977b748ebdbd)

![image](https://github.com/resilience4j/resilience4j-spring-boot3-demo/assets/332234/61261d84-fe05-4b05-b963-a0765d598a13)

![image](https://github.com/resilience4j/resilience4j-spring-boot3-demo/assets/332234/ce5e61f7-4b0a-44eb-b2cf-22c59ebeb896)

**Comment by nagkumar** [comment]
Also, the password used for Graphana was admin/admin

Further info in Readme.md would help such as how to view the graphs and simulate failures and see the recovery happening etc.. currently we can only see empty views 

<img width="1195" alt="image" src="https://github.com/resilience4j/resilience4j-spring-boot3-demo/assets/332234/0e042bb9-0d08-47f6-ab99-25cd68c41d11">
