### ISSUE TITLE
High dependence with spring-boot-starter-aop

### ISSUE THREAD

**Issue by mansillafederico** [resilience4j/resilience4j-spring-boot3-demo#8]
Hello there!

I've trying to implement a simple Retry with Java 17 and spring boot 3.1.2 with no success.

After clone this demo I figure out that if you remove the "spring-boot-starter-aop" dependency and all the code associated with it the @Retry annotation doesn't work anymore.

I didn't find this dependency on the documentation but maybe is a plus just put a note there.

Good job team!

**Comment by RobWin** [comment]
Hi, 
do you mean this?
https://resilience4j.readme.io/docs/getting-started-3#setup

**Comment by mansillafederico** [comment]
Yeah, thanks RobWin!
